# Shafiqul Alam Khan

# EE 5323 Digital Image Processing

# Homework 1

# Due Date: 1/24/2023

In [1]:
# import the builtin time & ctime module
from time import process_time, perf_counter

# Start counting time
st = process_time()

## 2. Define two variables, "matrix_a" and "matrix_b", that are 10,000x10,000 matrices filled with random values between 0 and 1. (Use numpy random capabilities)
### a. Print the generated matrix_a & matrix_b

In [2]:
# importing numpy
import numpy as np

# Generate matrix_a
matrix_a = np.random.rand(10000, 10000)

# Generate matrix_b
matrix_b = np.random.rand(10000, 10000)

# Print matrix_a
print(matrix_a)

# Print matrix_b
print(matrix_b)

[[0.59321119 0.52589135 0.87468681 ... 0.17730985 0.35347223 0.03123697]
 [0.97083456 0.23367593 0.81461232 ... 0.38523674 0.13783963 0.38268672]
 [0.34836982 0.11314288 0.95310627 ... 0.71657029 0.63264736 0.18158931]
 ...
 [0.35284487 0.26516167 0.21666351 ... 0.68116829 0.62730179 0.48405729]
 [0.67943171 0.61624286 0.94830517 ... 0.05981799 0.43752374 0.29878795]
 [0.69526373 0.14834842 0.9650108  ... 0.88860927 0.64528286 0.42108902]]
[[0.62782633 0.03627533 0.87536342 ... 0.7056558  0.74761762 0.88614155]
 [0.59191851 0.48714484 0.3781678  ... 0.20425218 0.99995557 0.1431898 ]
 [0.71069593 0.07968946 0.83283519 ... 0.94095021 0.77959568 0.49407614]
 ...
 [0.85818455 0.18112814 0.47504767 ... 0.25109661 0.18985285 0.73031691]
 [0.59309933 0.40229582 0.10935716 ... 0.77634612 0.36869221 0.63070388]
 [0.54065803 0.14269512 0.23081889 ... 0.4598961  0.08025252 0.7243829 ]]


## 3. Define a function called "matrix_addition" that takes in two matrices and returns the sum of the two matrices.
### a. Print the sum of matrix_a and matrix_b

In [3]:
# Defining matrix_addition function
def matrix_addition(X, Y):
    """Add two matrices"""
    result = X + Y
    return result

# Print the sum of two matrices
matrix_addition(matrix_a, matrix_b)

array([[1.22103752, 0.56216668, 1.75005022, ..., 0.88296564, 1.10108985,
        0.91737852],
       [1.56275307, 0.72082077, 1.19278012, ..., 0.58948892, 1.1377952 ,
        0.52587652],
       [1.05906575, 0.19283234, 1.78594147, ..., 1.6575205 , 1.41224304,
        0.67566545],
       ...,
       [1.21102942, 0.44628981, 0.69171118, ..., 0.93226489, 0.81715464,
        1.2143742 ],
       [1.27253104, 1.01853868, 1.05766233, ..., 0.83616411, 0.80621595,
        0.92949183],
       [1.23592175, 0.29104354, 1.19582969, ..., 1.34850536, 0.72553538,
        1.14547193]])

## 4. Define a function called "matrix_multiplication" that takes in two matrices and returns the product of the two matrices.
### a. Print the product of matrix_a and matrix_b
### b. Calculate and print the time it takes to calculate the multiplication operation

In [4]:
# Defining matrix_multiplication fuction
def matrix_multiplication(X, Y):
    """product of two matrices"""
    result = np.dot(X, Y)
    return result

# Start of counting time
start = perf_counter()

# Print the product of two matrices
print(matrix_multiplication(matrix_a, matrix_b))

# End of counting timne
end = perf_counter()

# Calculation of time
time = (end - start)

print("\n Execution time: "+str(time))

[[2505.84586836 2517.78007335 2501.12798956 ... 2514.41451871
  2503.45643129 2493.20564247]
 [2537.32832531 2525.57941173 2524.8206611  ... 2526.15081054
  2523.47169428 2508.40560419]
 [2518.49178239 2513.57963557 2501.48999782 ... 2503.85329473
  2505.8231972  2490.42637024]
 ...
 [2518.3287373  2536.58947907 2494.75430418 ... 2515.42718748
  2508.6872537  2499.70546552]
 [2531.5039499  2534.03880633 2526.58904543 ... 2535.6840269
  2526.40497078 2509.44699932]
 [2481.96257356 2516.69593135 2478.90752176 ... 2494.90931466
  2501.61905728 2473.55312196]]

 Execution time: 12.9022379


## 5.Define a function called "matrix_transpose" that takes in a matrix and returns the transpose of the matrix.
### a. Print the transpose of matrix_a
### b. Print the transpose of matrix_b

In [5]:
# Defining matrix_transpose function
def matrix_transpose(X):
    """Transpose of a matrix"""
    result = np.transpose(X)
    return result

# Print transpose of matrix_a
print(matrix_transpose(matrix_a))

# Print transpose of matrix_b
print(matrix_transpose(matrix_b))

[[0.59321119 0.97083456 0.34836982 ... 0.35284487 0.67943171 0.69526373]
 [0.52589135 0.23367593 0.11314288 ... 0.26516167 0.61624286 0.14834842]
 [0.87468681 0.81461232 0.95310627 ... 0.21666351 0.94830517 0.9650108 ]
 ...
 [0.17730985 0.38523674 0.71657029 ... 0.68116829 0.05981799 0.88860927]
 [0.35347223 0.13783963 0.63264736 ... 0.62730179 0.43752374 0.64528286]
 [0.03123697 0.38268672 0.18158931 ... 0.48405729 0.29878795 0.42108902]]
[[0.62782633 0.59191851 0.71069593 ... 0.85818455 0.59309933 0.54065803]
 [0.03627533 0.48714484 0.07968946 ... 0.18112814 0.40229582 0.14269512]
 [0.87536342 0.3781678  0.83283519 ... 0.47504767 0.10935716 0.23081889]
 ...
 [0.7056558  0.20425218 0.94095021 ... 0.25109661 0.77634612 0.4598961 ]
 [0.74761762 0.99995557 0.77959568 ... 0.18985285 0.36869221 0.08025252]
 [0.88614155 0.1431898  0.49407614 ... 0.73031691 0.63070388 0.7243829 ]]


## 6. Calculate and print the time it takes to calculate the entire program

In [6]:
# end of counting time
en = process_time()
total_time = en - st
print("Total Execution time: "+ str(total_time))

Total Execution time: 52.8125


## 7. Calculate the percentage of the multiplication time to the time of execution of the whole program

In [8]:
print(str(((total_time-time)/total_time)*100) + "%")

75.56972705325443%
